version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list

      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server kafka-broker-2:9092 --topic user-created-event-topic --delete --if-exists
      
      echo -e 'Creating kafka topics'
      kafka-topics --create --topic user-created-event-topic --bootstrap-server kafka-broker-2:9092 --replication-factor 1 --partitions 3

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-broker-2:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}