version: '3.7'
services:
  mysql-user-service:
    image: mysql:5.7.39-debian
    restart: always
    #    command: --lower_case_table_names=1
    container_name: mysql-user-service
    hostname: mysql-user-service
    networks:
      - kafka_msa-prototype
#      - ${GLOBAL_NETWORK:-kafka}
#      - msa-infra
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=test1357
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1357
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
networks:
  kafka_msa-prototype:
    external: true
#    driver: bridge